server:
  port: 8888
  servlet:
    context-path: /api/v1


spring:
  application:
    name: algo-crazy-api
  profiles:
    active: local
  datasource:
    # type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dance8.fun:5432/algo_crazy_db
    username: liweiwei1419
    password: 123456
  #    druid:
  #      initial-size: 5
  #      min-idle: 5
  #      max-active: 20
  #      max-wait: 60000
  #      time-between-eviction-runs-millis: 60000
  #      min-evictable-idle-time-millis: 300000
  #      validation-query: SELECT 1
  #      test-while-idle: true
  #      test-on-borrow: false
  #      test-on-return: false
  #      pool-prepared-statements: true
  #      max-pool-prepared-statement-per-connection-size: 20
  #      filters: stat,wall,log4j
  #      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  data:
    redis:
      host: dance8.fun
      port: 6379
      password: 123456
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: 10000ms
          max-idle: 8
          min-idle: 0
  minio:
    access-key: pM4vquf3BqwzQHbvUyvO
    secret-key: ACxa2JrShmH8qwGqdC8KRqz9sy5oTtmK8F0NDApE
    url: https://minio.dance8.fun
    bucket-name: algo-crazy
  mail:
    host: smtp.163.com
    username: liwei1419@163.com
    password: KYRWESQJIWXQAOWF
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true  # 启用 SSL 加密
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory  # 指定 SSL 套接字工厂
          port: 465  # 指定 SSL 端口


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    jdbc-type-for-null: null

  global-config:
    db-config:
      id-type: auto
      logic-delete-field: is_deleted
      logic-not-delete-value: false
      logic-delete-value: true
      schema: public

  type-aliases-package: com.suanfa8.algocrazyapi.entity
  mapper-locations: classpath:mapper/*.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.suanfa8.algocrazyapi.controller
knife4j:
  enable: true
  setting:
    language: zh_cn
  enhance:
    enable: false  # 禁用增强功能，解决版本兼容性问题
  basic:
    enable: false
  production: false

jwt:
  secret: 7ekaVma5Ud63zO8enUd9YcwQg8C8P/V7N0dFWHgjFI6Oz0DMwQQOggRevx+aviSfvte8cNg1Y/HbpVUpLx0zhg==
  # 过期时间，3600000 毫秒，1 小时
  expiration: 3600000

tencent:
  cos:
    secretId: AKIDd6LLFsELDpFPMDpCKG0VnrmMvNhuxpSv
    secretKey: NXVGn7E7mETUGn83kDSghT3SdaJo57JL
    region: ap-shanghai
    bucketName: suanfa8-1252206550
    prefix: https://suanfa8-1252206550.cos.ap-shanghai.myqcloud.com/suanfa8/

dingtalk:
  custom-robot-token: 38bb269585b2439c6ec0c291997b318caf8d5c594da4ef866c46fce914f62dc3
  user-id: 13671597056
  secret: SECf8723bce4b996782f7ea585fd2823bd5a713bc273820b3d6f2a80bb4152ae652

yuque:
  auth:
    token: W4VTVSDdHAxefbHKvY3G43fKIT2ZWj9R9lmI4JD9

frontend:
  url: http://localhost:5173