spring:
  application:
    name: springboot3-helloworld
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:postgresql://127.0.0.1:5432/algo_crazy_db
    username: liweiwei1419
    password: 123456
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: 10000ms
          max-idle: 8
          min-idle: 0