server:
  port: 8888


spring:
  application:
    name: springboot3-helloworld
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:postgresql://dance8.fun:5432/algo_crazy_db
    username: liweiwei1419
    password: 123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ??SQL??
    map-underscore-to-camel-case: true # ??????
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler # ????
    jdbc-type-for-null: null # ??JDBC???null???

  global-config:
    db-config:
      id-type: auto # ????
      logic-delete-field: isDeleted # ??????
      logic-not-delete-value: false # ????
      logic-delete-value: true # ???
      schema: public # PostgreSQL schema

  type-aliases-package: com.suanfa8.algocrazy.entity # ??????
  mapper-locations: classpath:mapper/*.xml # Mapper????