server:
  port: 8888
  servlet:
    context-path: /api/v1


spring:
  application:
    name: springboot3-helloworld
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:postgresql://dance8.fun:5432/algo_crazy_db
    username: liweiwei1419
    password: 123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  data:
    redis:
      host: dance8.fun
      port: 6379
      password: 123456
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: 10000ms
          max-idle: 8
          min-idle: 0
  minio:
    access-key: pM4vquf3BqwzQHbvUyvO
    secret-key: ACxa2JrShmH8qwGqdC8KRqz9sy5oTtmK8F0NDApE
    url: https://minio.dance8.fun
    bucket-name: algo-crazy


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ??SQL??
    map-underscore-to-camel-case: true  # ????????
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler # ????
    jdbc-type-for-null: null # ??JDBC???null???

  global-config:
    db-config:
      id-type: auto # ????
      logic-delete-field: isDeleted # ??????
      logic-not-delete-value: false # ????
      logic-delete-value: true # ???
      schema: public # PostgreSQL schema

  type-aliases-package: com.suanfa8.algocrazy.entity # ??????
  mapper-locations: classpath:mapper/*.xml # Mapper????

# springdoc-openapi????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.suanfa8.algocrazyapi.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn

jwt:
  secret: 123456
  # 过期时间，604800 秒，7 天
  expiration: 604800

tencent:
  cos:
    secretId: AKIDd6LLFsELDpFPMDpCKG0VnrmMvNhuxpSv
    secretKey: NXVGn7E7mETUGn83kDSghT3SdaJo57JL
    region: ap-shanghai
    bucketName: suanfa8-1252206550
    prefix: https://suanfa8-1252206550.cos.ap-shanghai.myqcloud.com/suanfa8/

